# Linear Regression

In [14]:
import torch

In [2]:
w = torch.tensor(2.0,requires_grad=True)
b = torch.tensor(-1.0,requires_grad=True)

In [8]:
def forward(x):
    yhat = w*x+b
    return yhat

In [9]:
x = torch.tensor([1.0])
yhat = forward(x)
print(yhat)

tensor([1.], grad_fn=<AddBackward0>)


In [10]:
x = torch.tensor([[1.0],[2.0]])
print("The shape of x: ",x.shape)

The shape of x:  torch.Size([2, 1])


In [11]:
yhat = forward(x)
print("The prediction: ",yhat)

The prediction:  tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


In [13]:
x = torch.tensor([[1.0],[2.0],[3.0]])
yhat = forward(x)
print(yhat)

tensor([[1.],
        [3.],
        [5.]], grad_fn=<AddBackward0>)


In [15]:
from torch.nn import Linear
torch.manual_seed(1) # this is for randomness

In [16]:
lr = Linear(in_features=1,out_features=1,bias=True)
print("Parameters w and b: ",list(lr.parameters()))

Parameters w and b:  [Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [19]:
print("Python dictionary: ",lr.state_dict())
print("Keys: ",lr.state_dict().keys())
print("Values: ",lr.state_dict().values())

Python dictionary:  OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])
Keys:  odict_keys(['weight', 'bias'])
Values:  odict_values([tensor([[0.5153]]), tensor([-0.4414])])


In [21]:
print("Weight: ",lr.weight)
print("Bias: ",lr.bias)

Weight:  Parameter containing:
tensor([[0.5153]], requires_grad=True)
Bias:  Parameter containing:
tensor([-0.4414], requires_grad=True)


In [22]:
# Make the prediction at x = [[1.0]]

x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.0739]], grad_fn=<AddmmBackward>)


In [23]:
x=torch.tensor([[1.0],[2.0],[3.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.0739],
        [0.5891],
        [1.1044]], grad_fn=<AddmmBackward>)


# Custom modules

In [24]:
# Library for this section

from torch import nn

In [25]:
class LR(nn.Module):
    def __init__(self,input_size,output_size):
        super(LR,self).__init__()
        self.linear = nn.Linear(input_size,output_size)
    
    def forward(self,x):
        out = self.linear(x)
        return out

In [26]:
# Create the linear regression model. Print out the parameters.

lr = LR(1, 1)
print("The parameters: ", list(lr.parameters()))
print("Linear model: ", lr.linear)

The parameters:  [Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [27]:
# Try our customize linear regression model with multiple input

x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.2755],
        [0.0816]], grad_fn=<AddmmBackward>)
