In [1]:
# Import the libraries and set the random seed

from torch import nn
import torch
torch.manual_seed(1)

In [2]:
w = torch.tensor([[2.0],[3.0]],requires_grad = True)
b = torch.tensor([[1.0]],requires_grad=True)

In [3]:
def forward(x):
    yhat = torch.mm(x,w) + b
    return yhat

In [4]:
x = torch.tensor([[1.0,2.0]])
yhat = forward(x)
print("The result: ",yhat)

The result:  tensor([[9.]], grad_fn=<AddBackward0>)


## Each Row 

In [5]:
X = torch.tensor([[1.0,1.0],[1.0,2.0],[1.0,3.0]])

In [6]:
yhat = forward(X)
print(yhat)

tensor([[ 6.],
        [ 9.],
        [12.]], grad_fn=<AddBackward0>)


In [10]:
model = nn.Linear(2,1)

In [22]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.3319, -0.6657]], requires_grad=True), Parameter containing:
tensor([0.4241], requires_grad=True)]


In [8]:
yhat = model(x)
print(yhat)

tensor([[-0.3969]], grad_fn=<AddmmBackward>)


In [9]:
yhat = model(X)
print(yhat)

tensor([[-0.0848],
        [-0.3969],
        [-0.7090]], grad_fn=<AddmmBackward>)


## Custom Moduels

In [18]:
class linear_regression(nn.Module):
    def __init__(self,input_size,output_size):
        super(linear_regression,self).__init__()
        self.linear = nn.Linear(input_size,output_size)
        
    def forward(self,x):
        yhat = self.linear(x)
        return yhat

In [19]:
module = linear_regression(2,1)

In [20]:
# Print model parameters

print("The parameters: ", list(model.parameters()))

The parameters:  [Parameter containing:
tensor([[ 0.3319, -0.6657]], requires_grad=True), Parameter containing:
tensor([0.4241], requires_grad=True)]


In [23]:
X = torch.tensor([[11.0,12.0,13,14],[11,12,13,14]])

In [24]:
module = linear_regression(4,1)

In [25]:
yhat = module(X)
print(yhat)

tensor([[3.6731],
        [3.6731]], grad_fn=<AddmmBackward>)
